### ISSUE TITLE
Request info is not showing

### ISSUE THREAD

**Issue by rolandsusans** [malyshev/yii-debug-toolbar#131]
Some of panel info is missing:

![9d0dafb3514f11a860a8c3c6675738f6](https://cloud.githubusercontent.com/assets/6154604/7633215/80b1f834-fa5b-11e4-8ce5-b82f973ce26e.png)
![bb756d7ad79f400453d3fd99ca790ee9](https://cloud.githubusercontent.com/assets/6154604/7633216/80b22a02-fa5b-11e4-9776-8dfe6ad31998.png)
![4755648ea60cc827916705a1bb8d4d81](https://cloud.githubusercontent.com/assets/6154604/7633269/cc233e36-fa5b-11e4-8430-4c35aab9d361.png)

Although trace and database info is showing..

what can cause this problem?

**Comment by rolandsusans** [comment]
btw, i havent extracted extension under `app/protected/extensions`, i have little bit different structure `app/extensions`, what should i change to get this tool working?

**Comment by jashk** [comment]
Your SERVER_ADDR not match with REMOTE_ADDR

Try change YiiDebug.php line 37 for:

``` php
// } else if (empty($_SERVER['SERVER_ADDR']) || empty($_SERVER['REMOTE_ADDR']) || $_SERVER['SERVER_ADDR'] !== $_SERVER['REMOTE_ADDR']) {
} else if (empty($_SERVER['SERVER_ADDR']) || empty($_SERVER['REMOTE_ADDR'])) {
```

**Comment by rolandsusans** [comment]
wow thanks, that solved the problem, tnx for help. This is propably one of best yii-debug tools :+1:
