### ISSUE TITLE
Clicking the icon doesn't work

### ISSUE THREAD

**Issue by jarchuleta** [malyshev/yii-debug-toolbar#15]
Clicking the icon in the top right doesn't do anything. Is there java script missing? this is what the div looks like.

using version malyshev-yii-debug-toolbar-95c08de on yii 1.1.8

```    <a href="javascript:;//">TOOLBAR</a>

```

```

**Comment by gregmolnar** [comment]
are you using SQLite? Because I just got the same error and I noticed a bug when the application uses SQLite. I fixed it and pull request been made. In the meantime you can check out my fork but I will delete it once the pull request accepted.

**Comment by jarchuleta** [comment]
No I'm using MySQL. I think it an issue with yii 1.8

**Comment by gregmolnar** [comment]
It is odd. It works well for me with Yii 1.8 and MySQL. It would be very helpful if you would be able to check the html source of the page where it's not working and let me know if there is any PHP error at the bottom part.

**Comment by malyshev** [comment]
Try the latest version

**Comment by jarchuleta** [comment]
The latest version has the same behavior. but this time if there is any jquery on the page. I get javascript errors.

**Comment by vandamm** [comment]
It may be that you already have jquery library added to the page not via Yii asset system. In this case jquery that was added automatically by Yii can conflict with your existing one.

**Comment by jarchuleta** [comment]
This seems to be resolved now with the version I downloaded in January: 999f95e

**Comment by black-lotus** [comment]
for me, it's more complicated since the DOM doesn't appear.
this is my config
 array(
'class'=>'ext.yii-debug-toolbar.YiiDebugToolbarRoute',
'ipFilters'=>array('127.0.0.1','192.168.1.215'),
),
