### ISSUE TITLE
wrong links when base tag is present

### ISSUE THREAD

**Issue by mck89** [malyshev/yii-debug-toolbar#25]
If the site includes a &lt;base&gt; tag the toolbar links always redirect you to the base url when clicked.
For example let's say that you have a &lt;base href="http://test.com/"&gt; in your template and you are visiting an internal page like http://test.com/foo/bar.html, if you click on a link of the toolbar you will be redirected to http://test.com#yw1, this makes impossible to debug internal pages.
This happens because the href of the links is in format "#name", to fix it you can simply include the current page url before the fragment.

**Comment by malyshev** [comment]
Closed as outdated
