### ISSUE TITLE
No toolbar is shown if YII_DEBUG is set to false

### ISSUE THREAD

**Issue by mytskine** [malyshev/yii-debug-toolbar#28]
If the constant YII_DEBUG is set to false, then the debug toolbar is initialized (its JS is loaded) but it is not shown (no HTML).
Tested on a fresh install of Yii 1.1.8 whith the latest code for yii-debug-toolbar.

**Comment by malyshev** [comment]
Cannot reproduce. Please check may already fixed.

**Comment by malyshev** [comment]
Closed as outdated
