### ISSUE TITLE
CClientScript::POS_END

### ISSUE THREAD

**Issue by marcodeltongo** [malyshev/yii-debug-toolbar#3]
Hello,

first of all, very good work !!!

I needed to add CClientScript::POS_END to the registerScriptFile call on line 153 of "YiiDebugToolbar.php".

E.g.: $cs->registerScriptFile($this->assetsUrl . '/yii.debug.toolbar.js', CClientScript::POS_END);

The reason is that I have this setup:

'clientScript' => array(
            'scriptMap' => array(
                'jquery.js' => false,
                'jquery-ui.js' => false,
                'jquery.min.js' => false,
                'jquery-ui.min.js' => false,
                'jquery.metadata.js' => false,
            ),
            'coreScriptPosition' => CClientScript::POS_END,
)

**Comment by malyshev** [comment]
Thanks, fixed
