### ISSUE TITLE
Property "SiteController.actionParams" is not defined.

### ISSUE THREAD

**Issue by wejder** [malyshev/yii-debug-toolbar#35]
Description

Property "SiteController.actionParams" is not defined.

Source File

/var/www/yii/4/tomik/protected/extensions/yii-debug-toolbar/components/YiiDebugViewRenderer.php(77)

00065:                 'render',
00066:                 'renderPartial'
00067:             )) )
00068:             {
00069:                 break;
00070:             }
00071:         }
00072: 
00073:         array_push($this->_debugStackTrace, array(
00074:             'context'=>$context,
00075:             'contextProperties'=>  get_object_vars($context),
00076:             'action'=> $context instanceof CController ? $context->action : null,
00077:             'actionParams'=> $context instanceof CController ? $context->actionParams : null,
00078:             'route'=> $context instanceof CController ? $context->route : null,
00079:             'sourceFile'=>$sourceFile,
00080:             'data'=>$data,
00081:             'backTrace'=>$backTraceItem,
00082:             'reflection' => new ReflectionObject($context)
00083:         ));
00084:     }
00085:  
00086: }

**Comment by malyshev** [comment]
Thank you, wejder.

This issue already fixed. Please check it.

Regards, Sergey

On Fri, Dec 2, 2011 at 12:15 AM, wejder <
reply@reply.github.com

**Comment by wejder** [comment]
thx :>
