### ISSUE TITLE
2nd Database Connection Error

### ISSUE THREAD

**Issue by BradStephens** [malyshev/yii-debug-toolbar#40]
I extended CActiveRecord to setup a second database connection to a data warehouse. I named the database connection "dw". The toolbar doesn't render on pages that use the dw connection. The rest of the page seems to render fine.

The toolbar is in the HTML, and if I force it to be display "block" instead of "none" I can see it. Further, if I force the SQL block to display, I can see info for the "db" connection, but not the "dw" connection.

This is the error in the Apache log:

PHP Fatal error:  Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /home/brad/projects/dca/protected/extensions/yii-debug-toolbar/YiiDebugToolbar.php on line 145

Server:

Ubuntu 10.04.2 LTS
PHP 5.3.2
Apache 2.2.14.

**Comment by malyshev** [comment]
Hi! Thanks for your feedback. These issues already fixed. Please update your local copy.
