### ISSUE TITLE
For console mode do not include JS

### ISSUE THREAD

**Issue by pentium10** [malyshev/yii-debug-toolbar#41]
If you run in console mode it kills the entire app for several reasons:

exception 'CException' with message 'CConsoleApplication and its behaviors do not have a method or closure named "getClientScript".' 

{main}CException: CConsoleApplication and its behaviors do not have a method or closure named "getViewRenderer".

**Comment by malyshev** [comment]
Do not connect the panel in the configuration of console applications (console.php). This tool is not intended for use in debugging of console applications. 
Only for web applications that generate a html page (page service).

**Comment by pentium10** [comment]
My console file extends from the web file, and inherits these.
