### ISSUE TITLE
Missing Сookie method

### ISSUE THREAD

**Issue by dotzero** [malyshev/yii-debug-toolbar#42]
После установки возникает ошибка:

``` javascript
TypeError: Object function (a,b){return new e.fn.init(a,b,h)} has no method 'cookie' [http://localhost/assets/1cbe31e6/yii.debug.toolbar.js:10]
```

В коде есть

&lt;script type=&quot;text/javascript&quot; src=&quot;/assets/51f54240/jquery.js&quot;&gt;&lt;/script&gt;
&lt;script type=&quot;text/javascript&quot; src=&quot;/assets/51f54240/jquery.cookie.js&quot;&gt;&lt;/script&gt;

**Comment by malyshev** [comment]
Ок, спасибо, проверю

**Comment by dotzero** [comment]
Так происходит из-за того что в верстке используется кастомный jQuery который грузится не через registerScript  и оверрайтит тот что используется в Yii, соотвественно и плагин jQuesry Cookie тоже отключается. 

Чтобы этого небыло я внес плагин для работы с cookie как один из методов в yii.debug.toolbar.js 

Возможно и не самое лучшее решение но ничего не смог придумтаь лучше.

**Comment by malyshev** [comment]
Да, я понял в чем проблема. Постараюсь в ближайшее время выложить фикс

**Comment by voskobovich** [comment]
При подключении тулбара к моему проекту полчаю вот такюу ошибку:

PHP notice
Trying to get property of non-object
protected/extensions/yii-debug-toolbar/views/yii_debug_toolbar.php(13)

$panel - не является объектом, почему так?

Я использую версию php 5.3

**Comment by malyshev** [comment]
Closed as outdated
