### ISSUE TITLE
Problem when using modules

### ISSUE THREAD

**Issue by joujou** [malyshev/yii-debug-toolbar#48]
I try to use the extension in an application with modules and it doesn't work. The PHP code produced by the extension is returned in the source.
I'm not sure it's because I use modules but with another app without modules, I worked perfectly.

**Comment by malyshev** [comment]
Could you please give me your config sample? Almost of my applications is modular, and I have no problems with it.

**Comment by joujou** [comment]
It seems I've solved my problem:
in fact it seems the problem was in my server config, in which
phpinfo() was disabled in php.ini.
The strange thing is that some URLs could work, the ones that didn't
use a path format (index.php?r=controller/action).
I had PHP code in my final output:

....

<div class="plus">+</div>

```
                    <div class="minus">–</div>
                                    &nbsp;/usr/local/YiiFramework/framework/web/CBaseController.php(119):
```

<strong>require</strong>(&quot;/Dev/Web/yii-annuaire/protected/extensions/yii-debug-toolbar/vie...&quot;)               </div>

```
            <div class="code"><pre><span class="ln">114</span>
```

$data=$_data_;
<span class="ln">115</span>         if($_return_)
<span class="ln">116</span>         {
<span class="ln">117</span>             ob_start();
<span class="ln">118</span>             ob_implicit_flush(false);

<span class="error"><span class="ln error-ln">119</span>
require($_viewFile_);
</span><span class="ln">120</span>             return ob_get_clean();
<span class="ln">121</span>         }
<span class="ln">122</span>         else
<span class="ln">123</span>             require($_viewFile_);
<span class="ln">124</span>     }

</pre></div>            </td>
        </tr>
                        <tr class="trace app collapsed">
.........

In case, this is my config for modules, routes and log:

'defaultController' => 'recherche/structure',

'modules'=>array(
        // uncomment the following to enable the Gii tool
        'gii'=>array(
            'class'=>'system.gii.GiiModule',
            'password'=>'password',
            'ipFilters' => array('127.0.0.1'),
            'generatorPaths'=>array(
                'application.gii',   // a path alias
            ),
        ),
        'recherche'=>array(
        ),
        'backend'=>array(
        ),
    ),

'urlManager'=>array(
            'urlFormat'=>'path',
            'showScriptName'=>false,
            'caseSensitive'=>false,
            'rules'=>array(
                // Gii
                'gii'=>'gii',
                'gii/controller:w+'=>'gii/<controller>',
                'gii/controller:w+/action:w+'=>'gii/<controller>/<action>',

```
            // Routes generales
            '<module:\w+>/<controller:\w+>/<id:\d+>'=>'<module>/<controller>/view',
            '<module:\w+>/<controller:\w+>/<action:\w+>/<id:\d+>'=>'<module>/<controller>/<action>',
            '<module:\w+>/<controller:\w+>/<action:\w+>'=>'<module>/<controller>/<action>',

            // Routes generales
            //'<controller:\w+>/<id:\d+>'=>'<controller>/view',
            //'<controller:\w+>/<action:\w+>/<id:\d+>'=>'<controller>/<action>',
            //'<controller:\w+>/<action:\w+>'=>'<controller>/<action>',

            // Si aucune règle validée à ce stade et action précisée, routage
```

action recherche
                '<param_controller>/action:w+'=>'recherche/<param_controller>/<action>',
                // Si aucune règle validée à ce stade et pas d'action, routage
recherche (action par défaut)
                '<param_controller>'=>'recherche/<param_controller>',
            ),
        ),
'log'=>array(
            'class'=>'CLogRouter',
            'routes'=>array(
                array(
                    'class'=>'ext.yii-debug-toolbar.YiiDebugToolbarRoute',
                    'ipFilters'=>array('127.0.0.1'),
                ),
        ),

2012/2/20 Sergey Malyshev
reply@reply.github.com:

> Could you please give me your config sample? Almost of my applications is modular, and I have no problems with it.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/malyshev/yii-debug-toolbar/issues/48#issuecomment-4051438

## 

Cordialement,

Jean-Pierre Jounier

**Comment by joujou** [comment]
The problem was that phpinfo() was disabled in php.ini. The strange thing is that it seemed to work for some URLs without path format. When it didn't work, some PHP code was output in the final source code.

**Comment by malyshev** [comment]
Closed as outdated. phpinfo not used anymore
