### ISSUE TITLE
php 5.4 Illegal string offset 'class'

### ISSUE THREAD

**Issue by Siomkin** [malyshev/yii-debug-toolbar#49]
В php 5.4 выдаёт ошибку Illegal string offset 'class'
/extensions/yii-debug-toolbar/YiiDebugToolbar.php(186)
186  isset($config['class']) || $config['class'] = $id;

**Comment by hiegdk** [comment]
I'm seeing this issue as well.

**Comment by dm1try** [comment]
**hiegdk**,
did you use the patch?

**Comment by hiegdk** [comment]
downloaded a fresh copy - no change. Has this been merged into the main branch?

**Comment by JohnnyMa** [comment]
use the latest version, this bug is fixed already.
tried this commit 066dec1dcff6bd08678d70cf4df153cc218b895f, it works fine.

i think this issue should be closed ;)

**Comment by kmindi** [comment]
this has been fixed, can be closed

**Comment by voskobovich** [comment]
PHP notice
Trying to get property of non-object

protected/extensions/yii-debug-toolbar/views/yii_debug_toolbar.php(13)

$panel - no object, why?

Using php version 5.3

**Comment by malyshev** [comment]
Hi @voskobovich. Is your comment relates to this topic?
