### ISSUE TITLE
I get only bug icon in upper right corner of page and clicking on it does nothing

### ISSUE THREAD

**Issue by idrozd** [malyshev/yii-debug-toolbar#5]
Apache/2.2.4 (Win32) mod_ssl/2.2.4 OpenSSL/0.9.8k PHP/5.3.3 Server at localhost Port 80
That's what my Denwer installation says (russian WAMP or smth like that)

Windows XP SP3.

**Comment by davidtomsik** [comment]
The same result as idrozd reported.

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:2.0.1) Gecko/20100101 Firefox/4.0.1 || OpenSuse 11.4 
Server: Apache/2.2.17 (Linux/SUSE), PHP/5.3.5

**Comment by malyshev** [comment]
I think it has been related to issue #6. Now this issue is resolved. Please notify me if really solved and can be closed. Thanks.

**Comment by davidtomsik** [comment]
Malyshev you are right it was related to issue #6. Now, everything works fine for me.
Thank you!

**Comment by malyshev** [comment]
Thanks for all ))
