### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by stamm** [malyshev/yii-debug-toolbar#53]
I use standart Yii redirect in application: 

``` php
Yii::app()->request->redirect('/newpage'/);
```

And get error:

> Trying to get property of non-object
> /extensions/yii-debug-toolbar/yii-debug-toolbar/views/yii_debug_toolbar.php(9)

Print screen of back trace http://img707.imageshack.us/img707/1404/screenshot20120413at144.png

**Comment by malyshev** [comment]
Thanks

On Fri, Apr 13, 2012 at 12:50 PM, Rustam Zagirov
reply@reply.github.com
wrote:

**Comment by pablo-archenti** [comment]
Hi, I'm having the same problem when I do a 

Yii::app()->user->loginRequired();

in handleBeginRequest() method.

**Comment by damour** [comment]
same problem

**Comment by malyshev** [comment]
Unable to reproduce.
