### ISSUE TITLE
yiiDebugToolbar not defined (javascript)

### ISSUE THREAD

**Issue by peltronic** [malyshev/yii-debug-toolbar#59]
Hello,

I downloaded the Debug Toolbar today (7/5/12) from github, and followed the installation instructions.

I'm getting the following javascript error:

```
Uncaught ReferenceError: yiiDebugToolbar is not defined
```

on this line:

  (function($) {$(function(){yiiDebugToolbar.init()})}(jQuery));

I checked and the yii.debugtoolbar.js lib is installed under 'assets/84af4f51'. I also stepped through the php code and confirmed registerScriptFile() is being called for this file in YiiDebugToolbar.php.

Kind of stuck what's going on here. Is it a bug or is there some setup step I missed?

I'm running:

```
Yii 1.1.9
```

Thanks,

Peter

**Comment by malyshev** [comment]
Fixed
