### ISSUE TITLE
Alias "ext.yii-debug-toolbar.YiiDebugToolbarRoute" is invalid. Make sure it points to an existing PHP file and the file is readable.

### ISSUE THREAD

**Issue by Boran** [malyshev/yii-debug-toolbar#63]
I'm now to yii, and was very interested to your toolbar, but have the above error after activating.

The document (if I understand correctly) states to extract the tool into protected/extensions, i.e protected/extensions/yii-debug-toolbar/YiiDebugToolbarRoute.php  exists as a path

I put the following in main.php:
     'routes'=>array(
        array(
                'class'=>'ext.yii-debug-toolbar.YiiDebugToolbarRoute',

is "extensions" the right place to put it?  Why is "ext." above?

thanks in advance

**Comment by Stas-Ghost** [comment]
If you checkout extension from GitHub, try to change path to
`'class'=>'ext.yii-debug-toolbar.yii-debug-toolbar.YiiDebugToolbarRoute'`

Extensions is a right place, `ext.` is [alias](http://www.yiiframework.com/doc/guide/1.1/en/basics.namespace#root-alias) for this folder.

**Comment by Boran** [comment]
So I didn't know about aliases, thanks for the link.

Now it works, Thanks!

FYI:
Yes, I pulled the extension from github. The tar.gz file was extracted gave a sub folder "malyshev-yii-debug-toolbar-0ff45a6". Within that folder there was a  yii-debug-toolbar, which was moved to protected/extensions

~/yii/testdrive/protected$ ls -al ext/yii-debug-toolbar
total 60
-rwxrwxr-x 1 boran boran  771 2012-09-24 11:30 YiiDebugViewHelper.php
-rwxrwxr-x 1 boran boran 7263 2012-09-24 11:30 YiiDebugToolbarRoute.php
-rwxrwxr-x 1 boran boran 5182 2012-09-24 11:30 YiiDebugToolbar.php
-rwxrwxr-x 1 boran boran 1776 2012-09-24 11:30 YiiDebugToolbarPanel.php
-rwxrwxr-x 1 boran boran 1377 2012-09-24 11:30 YiiDebug.php

And in main.php:
'class'=>'ext.yii-debug-toolbar.YiiDebugToolbarRoute',

**Comment by kmindi** [comment]
Yes this extension should not create an additonal directory. The problem is for example if you add the debug toolbar as submodule then you get one folder ext/yii-debug-toolbar, and within that folder is the content of this git repository, which means another folder => ext/yii-debug-toolbar/yii-debug-toolbar...
