### ISSUE TITLE
Панель не отображается когда в логах ничего нет

### ISSUE THREAD

**Issue by ghost** [malyshev/yii-debug-toolbar#75]
Собственно в теме всё и написано. Как проверить:
1. Создаём пустой webapp в Yii 1.1.13
2. Подключаем в него yii-debug-toolbar согласно мануалу
3. В index.php комментируем строку:

``` php
defined('YII_DEBUG') or define('YII_DEBUG',false);
```

Панель пропадёт. Появится если, например, в контроллере сделать Yii::log('something');

Решение найдено, будет запушено ниже :) Это место аналогично как для dev так и для main ветки.

**Comment by ghost** [comment]
Хммм... оно еще один issue создало... 76-й... Ну и ладно :) Главное что сюда решение тоже прилетело.

**Comment by malyshev** [comment]
Proposed code fix creates another problem. Panels generates twice when logs not empty.
