### ISSUE TITLE
jQuery - включать только в том случае если нет jQuery в проекте

### ISSUE THREAD

**Issue by RooTooZ** [malyshev/yii-debug-toolbar#98]
Суть проблемы заключается в том что если мы подключили уже в проекте Jquery то не нужно подключать еще одну!
Вызываются ошибки

**Comment by malyshev** [comment]
Working as designed. No changes requires. Use scriptMap property of CClientScript component to disable loading of system jquery (or any other) library.

**Comment by RooTooZ** [comment]
You could tell how to do it?

**Comment by malyshev** [comment]
Add to your app config -> components 

```
'clientScript' => array(
    'scriptMap' => array(
        'jquery.js' => false
    )
),
```

**Comment by RooTooZ** [comment]
Thanks!

**Comment by malyshev** [comment]
:metal:
