### ISSUE TITLE
Declaration of YiiDebugToolbarRoute::collectLogs() should be compatible with CLogRoute::collectLogs($logger, $processLogs = false)

### ISSUE THREAD

**Issue by andycaramba** [malyshev/yii-debug-toolbar#99]
Только что обновил тулбар и на Yii 1.1.14 получил ошибку

<pre>
Declaration of YiiDebugToolbarRoute::collectLogs() should be compatible with CLogRoute::collectLogs($logger, $processLogs = false)
</pre>

Так понимаю проблема после этого коммита - https://github.com/malyshev/yii-debug-toolbar/commit/c9aa1a07c6692f5b67986b17de0cdb6a9b060dee#diff-78c84c6d8b1db8307d74ac23bf63cc76R183

**Comment by malyshev** [comment]
Fixed
